spring:
  datasource:
    url: jdbc:mysql://47.120.35.241:3306/assistant?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: Wanghx8870639!
  data:
    redis:
      host: 47.120.35.241
      port: 6379
      password: Wanghx8870639!
      timeout: 1000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


